### ISSUE TITLE
Readme ends with 11

### ISSUE THREAD

**Issue by gbraad** [vwbusguy/QORBLE#1]
```
This should also run fine on Windows, but the above command may need adjusted (qb64.exe, etc.)11
```

Was it meant to say Windows 11? If so, it is wrong as this would be the case for all Windows versions. I believe it is just garbage/wrong edit.

**Comment by vwbusguy** [comment]
All versions that qb64 supports.   They only very recently dropped support for XP and older, IIRC.   

The 11 at the end is a typo.   Good catch!  If you'd prefer to submit a PR, that would be awesome.   Otherwise, I'll fix it later on tonight.

**Comment by vwbusguy** [comment]
Fixed.  Many thanks for reporting this, @gbraad!
